api = "0.10"

[buildpack]
id = "hone/syft"
version = "0.1.0"
name = "Syft"

sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
